In [1]:
import numpy as np
import faiss

#dimension = 128   # dimensions of each vector                         
#n = 200    # number of vectors                   
#np.random.seed(1)             
#db_vectors = np.random.random((n, dimension)).astype('float32')

Loading faiss with AVX2 support.
Loading faiss.


In [30]:
db_vectors.shape

(7, 196608)

In [26]:
from PIL import Image
import numpy as np

w, h = 224, 224
#data = np.zeros((h, w, 3), dtype=np.uint8)
#data[256, 256] = [255, 0, 0]
#db_vectors.
img = Image.fromarray(db_vectors, 'RGB')
#img.save('my.png')
img.show()

In [27]:
nlist = 5  # number of clusters
quantiser = faiss.IndexFlatL2(dimension)  
index = faiss.IndexIVFFlat(quantiser, dimension, nlist,   faiss.METRIC_L2)

In [28]:
print(index.is_trained)   # False
index.train(db_vectors)  # train on the database vectors
print(index.ntotal)   # 0
index.add(db_vectors)   # add the vectors and update the index
print(index.is_trained)  # True
print(index.ntotal)   # 200

False
0
True
200


In [29]:
nprobe = 2  # find 2 most similar clusters
n_query = 10  
k = 3  # return 3 nearest neighbours
np.random.seed(0)   
query_vectors = np.random.random((n_query, dimension)).astype('float32')

In [30]:
distances, indices = index.search(query_vectors, k)

In [31]:
distances

array([[15.770459, 16.773014, 17.17131 ],
       [16.476107, 18.52229 , 18.811913],
       [15.520995, 16.500256, 17.069542],
       [16.842718, 17.712341, 17.828487],
       [18.325392, 18.495464, 18.684456],
       [17.531885, 18.18179 , 18.331263],
       [16.840158, 17.03664 , 17.091755],
       [15.984037, 16.380917, 17.270592],
       [18.018503, 18.0761  , 18.766172],
       [17.113918, 17.385284, 17.65757 ]], dtype=float32)

In [11]:
s = load_image('./Testing Data/'+i).size
s

518400

In [30]:
imgs[0].reshape(s,1).T.tolist()

[[0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,


In [2]:
import os
from PIL import Image
import numpy as np
import pandas as pd

path = '/myfiles/DeepLearning/ml/projects/user/alaap/weapon_precision/test_output/general/safe/'
def load_image( infilename ) :
    img = Image.open( infilename )
    img.load()
    img = img.resize((256,256))
    data = np.asarray( img ,dtype = 'float32')
    return data

imgs = []
for i in os.listdir(path)[:2000]:
    imgs.append(load_image(path+i))
    #df = df.append(pd.Series([load_image('./Testing Data/'+i).reshape(s,1).T]),ignore_index=True)


In [3]:
len(imgs)

2000

In [13]:
del imgs

In [14]:
del db_vectors

In [4]:
db_vectors = np.array(imgs).reshape(len(imgs),-1)

In [5]:
db_vectors.shape

(2000, 196608)

In [9]:
img = Image.fromarray((db_vectors[0]).reshape(256,256,3), 'RGB')
#img.save('my.png')
img.show()

In [6]:
dimension = db_vectors.shape[1] #dimention
n = db_vectors[0]    # number of vectors

In [7]:
nlist = 100  # number of clusters
quantiser = faiss.IndexFlatL2(dimension)  
index = faiss.IndexIVFFlat(quantiser, dimension, nlist, faiss.METRIC_L2)

In [8]:
print(index.is_trained)   # False
index.train(db_vectors)  # train on the database vectors
print(index.ntotal)   # 0
index.add(db_vectors)   # add the vectors and update the index
print(index.is_trained)  # True
print(index.ntotal)   # 200

False
0
True
2000


In [9]:
nprobe = 3  # find 3 most similar clusters  
k = 5  # return 10 nearest neighbours   
#query_vectors = np.random.random((n_query, dimension)).astype('float32')

quesry_imgs = []
for i in os.listdir(path)[10:12]:
    quesry_imgs.append(load_image(path+i))
    #df = df.append(pd.Series([load_image('./Testing Data/'+i).reshape(s,1).T]),ignore_index=True)
    
query_vectors = np.array(quesry_imgs).reshape(len(quesry_imgs),-1)

In [22]:
del query_vectors
del quesry_imgs

In [10]:
distances, indices = index.search(query_vectors, k)

In [11]:
distances,indices

(array([[0.0000000e+00, 1.0313217e+09, 1.1199231e+09, 1.1787479e+09,
         1.1797402e+09],
        [0.0000000e+00, 1.1706296e+09, 1.2101453e+09, 1.2221033e+09,
         1.2259715e+09]], dtype=float32),
 array([[  10,  944, 1752, 1527,  197],
        [  11,  259,  671,  176, 1167]]))

In [12]:
indices

array([[  10,  944, 1752, 1527,  197],
       [  11,  259,  671,  176, 1167]])

In [17]:
imgs[10].sum()

37123760.0

In [20]:
img = Image.fromarray((db_vectors[10]).reshape(256,256,3), 'RGB')
#img.save('my.png')
img.show()

In [19]:
img = Image.fromarray((db_vectors[994]).reshape(256,256,3), 'RGB')
#img.save('my.png')
img.show()